# --- Motyw GitHub Pages  ---
theme: jekyll-theme-hacker

# --- Meta / SEO  ---
title: Sebastian Ciborowski — CV & Portfolio
description: Krótka wizytówka: linki do CV (PL/EN), „O mnie”, „Jak pracuję”, szkolenia i portfolio.

# --- Wykluczenia (nie renderuj tych ścieżek przez Jekyll) ---
exclude:
  - .github/
  - .gitignore
  - README.md
